### ISSUE TITLE
PDF highlighting: engine now in unireader

### ISSUE THREAD

**Issue by hwhw** [koreader/kindlepdfviewer#103] opened 2012-04-11 20:57 UTC
I've just checked in PDF highlighting. Bad thing however is that it is still buggy. And I really hope I did not break djvu highlighting. A quick check showed it was still working. But please test extensively.

I still have to fully grasp the highlighting code. I found some rough edges that were DJVU specific and tried to flesh them out. But PDF highlighting still does not work correctly regarding zoom and some other things.

**Comment by dpavlin** [comment] 2012-04-11 22:10
Great work. It works nicely with pdfs which have real text in them, but when I tried our `test/2col.pdf` or `test/tall.pdf` I got:

```
Program received signal SIGSEGV, Segmentation fault.
getPageText (L=0x85ac058) at pdf.c:356
356                     linebbox = ptr->text[0].bbox; // start with sensible default
```

I'm not quite sure how to correctly check if that first element exists, so this is just a report :-)

**Comment by houqp** [comment] 2012-04-12 02:14
WOW, that's fast!

The segfault pointed out by @dpavlin is caused by reference of null pointer `ptr->text`, is this null pointer expected?

> But PDF highlighting still does not work correctly regarding zoom

Zoomming is not supported in DjVu neither ;P Current highlighting code should only work in FIT_TO_CONTENT_WIDTH mode, if it works in other mode, then we are just lucky. :)

If needed, we can discuss re-designing the structure for text table returned by getPageText method here. Following is a typical return from djvulibre's get text call:

``` lisp
 (line 912 1199 2525 1264
  (word 912 1200 1078 1264 "0,297")
  (word 1272 1200 1400 1264 "0,02")
  (word 1417 1211 1432 1263 "1")
  (word 1632 1199 1799 1263 "0,000")
  (word 1992 1199 2044 1263 "0,")
  (word 2060 1210 2161 1262 "157")
  (word 2357 1199 2525 1263 "0,266"))
 (line 1224 1095 2736 1163
  (word 1224 1095 1478 1162 "Anhang")
  (word 1501 1110 1564 1163 "61")
  (word 1580 1110 1593 1147 ":")
  (word 1625 1095 1974 1162 "Ergebmsse")
  (word 1996 1110 2104 1162 "der")
  (word 2129 1109 2382 1162 "Modells")
  (word 2401 1110 2514 1163 "M4")
  (word 2532 1096 2736 1162 "(cont.)"))
 (line 1000 1008 2980 1077
  (word 1000 1008 1593 1077 "(Signiikanzniveau:")
  (word 1621 1022 1736 1074 "Fett")
  (word 1755 1042 1795 1058 "=")
  (word 1827 1012 1933 1076 "I%,")
  (word 1961 1022 2306 1077 "Fett/Kursiv")
  (word 2327 1042 2367 1058 "=")
  (word 2396 1012 2502 1076 "5%,")
  (word 2533 1023 2734 1077 "Kursiv")
  (word 2756 1042 2796 1058 "=")
  (word 2831 1009 2980 1076 "10%)"))
```

**Comment by dpavlin** [comment] 2012-04-12 09:18
What are your objections to current structure? It seems to me that we can implement search #75 using `getText` so I'm fine with current structure.

**Comment by houqp** [comment] 2012-04-12 09:42
I am OK with that structure because I am not the one who is hacking on PDF highlight support ;P

This structure is designed for DjVu highlight and fits to djvulibre's API, but I am not sure whether it still fits to MuPDF's.

**Comment by hwhw** [comment] 2012-04-12 12:36
I think the current structure is OK. However, at some point (I think after next release) I'd like to allow for a "reformatter". That is a tool that takes the text as returned by getText() and re-calculates lines and order of words. But we should wait with that for now, I think, and use the order in which the muPDF/djvulibre engines return the words.

The concept of "spans" in MuPDF is very similar to the concept of "lines" in djvulibre, I think. However, there will be multiple spans when the text formatting changes within a line (as a human reader would identify it). No biggie for now, I think.

However, when I find some time I would really like to factor out the "highlighting" engine from unireader. I think it is in itself big enough to justify to create an own class for it (that gets registered in unireader upon init()). It's hard enough already to read unireader.lua. But maybe we should focus on a rewrite (or better call it "big cleanup") after a release?

It would be great when we could have a general document coordinates to screen coordinates mapper function that gets used in _all_ the various places we might need it.

Searching for words will work well with the current structure. Also, the highlighting code for marking search hits also is already in place :-)

For release, I think, it would be great to have highlighting support in zoomed/rotated modes.
Otherwise, a release would be great. Features like crengine, screensaver awareness and the help screen are a big steps forward. And a lot of people will only look at the releases...

**Comment by hwhw** [comment] 2012-04-12 12:37
Oh, and I forgot this: I think I know why it segfaults when there is no text. Even "ptr" will probably be zero in that case. Will commit a fix soon.

**Comment by houqp** [comment] 2012-04-12 14:37
> The concept of "spans" in MuPDF is very similar to the concept of "lines" in djvulibre, I think. However, there will be multiple spans when the text formatting changes within a line (as a human reader would identify it). No biggie for now, I think.

Seems that this can only be fixed by reformatter. :)

> However, when I find some time I would really like to factor out the "highlighting" engine from unireader. I think it is in itself big enough to justify to create an own class for it (that gets registered in unireader upon init()). It's hard enough already to read unireader.lua. But maybe we should focus on a rewrite (or better call it "big cleanup") after a release?

Agree, unireader.lua has grown into a 2000+ lines. It's not friendly to new developers anymore and might become a maintainace nightmare in the future if we don't clean it up. 

> For release, I think, it would be great to have highlighting support in zoomed/rotated modes.
> Otherwise, a release would be great. Features like crengine, screensaver awareness and the help screen are a big steps forward. And a lot of people will only look at the releases...

Ha, I am very excited about the new release :)

**Comment by hwhw** [comment] 2012-04-13 17:49
So far so good. The fix I promised is commited. For now, I'm closing this one. However, API changes in MuPDF will force me to tackle this matter again.

**Comment by dpavlin** [comment] 2012-04-14 12:42
I also have strange problem with pdf highlighting: it works on emulator, but doesn't on device it doesn't and returns "no text in current view!" although getText does return content but it looks strange:

In emulator:

```
{
    [1] = {
        [1] = {
            ["word"] = "HyperDex:",
            ["y1"] = 97,
            ["x1"] = 140,
            ["x0"] = 72,
            ["y0"] = 78
        },
        [2] = {
            ["word"] = "A",
            ["y1"] = 97,
            ["x1"] = 155,
            ["x0"] = 144,
            ["y0"] = 78
```

and on Kindle:

```
{
    [1] = {
        [1] = {
            ["word"] = "HyperDex:",
            ["y1"] = -695,
            ["x1"] = 140,
            ["x0"] = 72,
            ["y0"] = -714
        },
        [2] = {
            ["word"] = "A",
            ["y1"] = -695,
            ["x1"] = 155,
            ["x0"] = 144,
            ["y0"] = -714
        },
```

Y coordinates seem to be flipped. I don't see any calls to `screenOffset` on Kindle, am I calling it correctly in `UniReader`?

Example pdf: http://hyperdex.org/papers/hyperdex.pdf

**Comment by houqp** [comment] 2012-04-14 12:48
I don't have time to test on kindle device yet, but a quick guess might be the negative y?

**Comment by houqp** [comment] 2012-04-14 12:52
On emu mode, _findFirstWordInView gives me this on the second page:

```
{
        ["word"] = "get(",
        ["y1"] = 84,
        ["x1"] = 103,
        ["x0"] = 78,
        ["y0"] = 72
}
```

Did you get your debug info from the same page?

**Comment by houqp** [comment] 2012-04-14 12:57
> Is my cross-compiler broken?

To tell you the truth, the highlight in PDF is not working on my kindle too ;P

I noticed it yesterday, but haven't have time to look into it yet, very likely to be caused by same issue you found.

**Comment by dpavlin** [comment] 2012-04-14 13:15
So this is blocker for #109

**Comment by dpavlin** [comment] 2012-04-14 14:06
I tried to replace `fz_identity` param of `fz_run_page` with `ctm = fz_scale(1, 1);` but it didn't help. Maybe @hwhw will know better solution :-)

**Comment by hwhw** [comment] 2012-04-14 16:40
I'll look into it now. Maybe a signedness / store length issue? Might have gotten a type wrong or something.

**Comment by hwhw** [comment] 2012-04-14 17:18
I cannot reproduce. It works flawlessly here. (I did the full clean & recompile approach)

Now I am a bit lost...

**Comment by hwhw** [comment] 2012-04-14 17:54
I vote for a compiler bug for now. Personally I'm using Sourcery's 2011.09-70 toolchain, which has gcc-4.6.1.

**Comment by dpavlin** [comment] 2012-04-14 23:30
I'm trying to duplicate that enviroment (and document that :-), but I'm getting following error on device:

```
./kpdfview: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./kpdfview)
```

I'm compiling with:

```
make customupdate HOST=arm-none-linux-gnueabi STATICLIBSTDCPP=`pwd`/arm-2011.09/arm-none-linux-gnueabi/libc/usr/lib/libstdc++.a
```

**Comment by hwhw** [comment] 2012-04-15 00:06
Yep, sorry, I should have added that that I also use such a staticlibstdcpp setting - and a full sysroot. Sorry, the latter is a bit harder to create, it won't be easy to replicate that. That sysroot has older glibc (and more important: glibc headers).

I have a sysroot directory for my kindle toolchain which basically contains /lib, /usr/lib, /usr/include for a kindle environment. Libraries are selected from the Kindle itself, the includes I have painstakingly assembled from the Amazon sources (it's hard because some headers need to be adapted).

Maybe I should just put that sysroot on rapidshare.

For today, it's a bit late, however. But it would be worth it, the combination of the new toolchain and that "old" sysroot has proven to be working nicely here.

**Comment by houqp** [comment] 2012-04-15 01:12
Oh... that's a tough one. I think we need to write a guide for toolchian setup after the new release :(

**Comment by houqp** [comment] 2012-04-17 03:03
The highlight support works in my kindle with latest code now. I guess we can close this now? @dpavlin, can you double check this?

**Comment by dpavlin** [comment] 2012-04-17 09:37
It indeed does. Even coordinates are correct now :-)

Did you notice that highlight always position cursor **behind** first word on page? Shouldn't it be before it?

**Comment by houqp** [comment] 2012-04-17 10:06
> Did you notice that highlight always position cursor behind first word on page? Shouldn't it be before it?

Fixed. :) closing for now.

**Closed as completed by houqp** 2012-04-17 10:06 UTC
Labels: Feature
