### ISSUE TITLE
font size for hotkeys' labels (pdf hyperlinks) dependent on the font size of the first hyperlink

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#385] opened 2012-10-07 12:31 UTC
If your page is typeset as follows:
font size of the first row (contains a hyperlink): 20 pt
the rest of the page: 10 pt.

pressing 'L' overlays the hotkeys' labels in size 20 pt, making the text unreadable.

**Comment by tigran123** [comment] 2012-10-07 12:35
Hmmm, do you mean to say that pressing 'L' makes it unclear which shortcut belongs to which link? If so, then yes, this would be a bug. But if you merely mean that pressing 'L' makes the _other_ text unreadable (i.e. text irrelevant for selecting the shortcut) then this is expected behaviour, as you are not expected to read the main text in 'L' mode --- you are only expected to select the shortcut OR to pess `Back` and return from L-mode.

**Comment by eLiNK2gl** [comment] 2012-10-07 12:42
@tigran123 in some cases it could be not clear.
The problem would typically come up on an index page, which contains many hyperlinks close to each other.

As usual, I'm ready to provide a link.

**Comment by dpavlin** [comment] 2012-10-07 12:55
That's true. I'm calculating font size based on first link to make sure that shortcut will overwrite just link and not content around it. I wondered if better solution would be to calculate font size for each link, but decided against it because of font init overhead for each link (without benchmarking, so I might be wrong). I will probably re-visit font sizing issue, but I don't have good solution yet.

I'm wondering should we have shortcuts in varying size on page (which might look ugly) or use "most common" size on page?

**Comment by tigran123** [comment] 2012-10-07 13:10
I think the best way forward is to examine the worst case scenario, i.e. the actual file. @eLiNK2gl can you please provide this file? Thanks.

**Comment by eLiNK2gl** [comment] 2012-10-07 15:15
@tigran123 you've got an email (at MR).

**Comment by tigran123** [comment] 2012-10-07 15:23
Oh yes, you are right, it is a bug. @dpavlin I'll forward the pdf file to your email now.

**Comment by tigran123** [comment] 2012-10-09 23:09
Fix merged into master.

**Closed as completed by tigran123** 2012-10-09 23:09 UTC
Labels: Bug

**Comment by eLiNK2gl** [comment] 2012-10-12 08:56
I do not know if it a bug.
So I am not opening a separate issue.
But the selection of the content (press 'X') is wrong on most of the pages in Stephens.pdf

**Comment by tigran123** [comment] 2012-10-12 09:01
Each PDF can define its own BoundingBox (it came from PostScript actually) internally, so it is not a bug. You can always override it with `Shift-X` and define your own bbox.
