### ISSUE TITLE
kpdfviewer crashed using jump history

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#269] opened 2012-09-10 14:03 UTC
while navigating though the jump history (shift + B) in a pdf file, the kpdfviewer crashed with the following error message:

"lua config error: ./unireader.lua:1693: bad argument #1 to 'ipairs' (table expected, got nil)"

**Comment by houqp** [comment] 2012-09-10 14:48
Could you tell us which version are you using? I can't find a way to reproduce in latest code.

**Comment by eLiNK2gl** [comment] 2012-09-10 15:52
@houqp '397d3aa037'
By navigating I meant calling up the jump history (Shift + B), selecting an item and pressing 'Enter'.

**Comment by tigran123** [comment] 2012-09-10 16:22
Oh, line 1693 points to my code in UniReader:findTOCpos(). I will investigate, leave it to me.

**Comment by tigran123** [comment] 2012-09-10 16:26
@eLiNK2gl I just tested it on a PDF file and cannot reproduce it. Can you please tell me which steps you performed to cause this to happen?

**Comment by tigran123** [comment] 2012-09-10 16:28
@eLiNK2gl 'Enter' is not a valid key for menus, unless you are using KDXG with long enough menus to reach it as a shortcut. On a K3 pressing 'Enter' in a menu will cause nothing to happen, which is (and always was) the expected behaviour.

**Comment by tigran123** [comment] 2012-09-10 16:32
Also, that code is never called from jump history, but only from "show table of contents" function, i.e. "T". Are you sure you were not navigating Table of Contents?

**Comment by eLiNK2gl** [comment] 2012-09-10 17:40
hmm... now I am not so sure.

Actually, I was going to test the bookmarking feature but mixed it up and called the jump history instead.
By 'Enter' I meant the middle key of the five-way.

I could have unintentionally pressed some other button.
But I was not looking at the dispay at the moment. Just saw afterwards that the kpdfviewer crashed.
(It would be probably the only reasonable explanation)
Sorry for the mix-up.

**Comment by tigran123** [comment] 2012-09-10 17:59
@eLiNK2gl  No problem at all. If you can reproduce it again please tell me the exact steps and I will try to fix it.

**Comment by tigran123** [comment] 2012-09-10 18:05
Ah, I think I have reproduced it now. The sequence of steps is this:
1. Open some PDF file on a page other than 1.
2. Go to page 1 manually (via "G" command enter "1")
3. Press "T" to get TOC, the crash follows:

lua config error: ./unireader.lua:1694: bad argument #1 to 'ipairs' (table expected, got nil)

Line number 1694 in my code is the same as 1693 in the one you are running because I just added one Debug() statement.

Ok, I will investigate now, leave it with me.

**Comment by tigran123** [comment] 2012-09-10 18:14
Ok, I know why this is happening. The self.toc is not nil even though we never entered showToc(). It was populated via some other callers of fillToc(). So, as a result, our call (via "T") of "Show Table of Contents" function skips the required initialization of self.toc_curidx_to_x and crashes findTOCpos() function.

Ok, I am going to the swimming pool now (can't keep my daughter waiting for too long), but when I come back I'll think of a proper way to fix it. You can consider it fixed by tomorrow morning :)

**Comment by tigran123** [comment] 2012-09-10 21:41
The fix is in the pull request #272 so I am closing this issue.

**Closed as completed by tigran123** 2012-09-10 21:41 UTC
Labels: Bug

**Comment by houqp** [comment] 2012-09-11 03:36
You have a lovely daughter :)

**Comment by tigran123** [comment] 2012-09-11 09:47
@houqp  Thank you, yes, even two of them, but the youngest is too young to go to the swimming pool yet :)
