### ISSUE TITLE
file manager menu on Touch 

### ISSUE THREAD

**Issue by th0mass** [koreader/kindlepdfviewer#749] opened 2013-02-18 07:07 UTC
when I return from a file to file manager the menu doesn't appear anymore (no problem on the first launch) 
since now I can use the home button no problem for me; but it could be problem for the paperwhite users.

used Kindle Touch 5.3.2. and the latest nighly build available(gdb8872c) and launched the app via KUAL

**Comment by chrox** [comment] 2013-02-18 10:02
This bug is confirmed. As `lipc-set-prop com.lab126.pillow displayChrome true` is not valid when KPV is launched by KUAL, one way to restore the chromeBar is to stop the pillowd process before running kpdf.sh with this command `killall -stop pillowd` and continue pillowd after exiting kpdf with `killall -cont pillowd`. One problem with this workaround is that KPV cannot resume from screensaver automatically when pressing the power button.

**Comment by chrox** [comment] 2013-02-18 10:09
@houqp Did you try to save the screensaver by running `killall -cont pillowd` just before the reader resuming from the SS. And did it work?

**Comment by houqp** [comment] 2013-02-18 17:33
Hopefully I can test it tonight when I get home. So can we still capture power button events after killed pillowd?

**Comment by twobob** [comment] 2013-02-18 18:25
erk... if there is anything we can do "our end" just say the word.

updated the "known issues" to reflect this for now.
http://www.mobileread.com/forums/showthread.php?p=2414040#post2414040

**Comment by houqp** [comment] 2013-02-19 02:59
Hey, I tried this on my PW, and stop pillowd works fine for me. I am able to switch back and forth between KPV and SS.

**Comment by th0mass** [comment] 2013-02-19 06:29
Can I propose an extra item for the file manager menu:  return to the current file (ie like a back button)

**Comment by houqp** [comment] 2013-02-19 14:55
how about adding a read history page so you can back to more files?

**Comment by th0mass** [comment] 2013-02-19 17:04
that's better :+1:

**Comment by houqp** [comment] 2013-02-19 21:58
Can anyone else confirm about the `stop pillowd` hack?

**Comment by th0mass** [comment] 2013-02-19 22:17
Adding the "Exit" into "Document menu" could be a temp soln for the paperwhite users. 

(these lines into 67th line of the readermenu.lua )

```
table.insert(self.item_table, {
        text = "Exit",
        callback = function()
            os.exit(0)
        end
    })
end
```

**Comment by houqp** [comment] 2013-02-21 14:50
Yes, add "exit" into document menu is a good idea.

Still don't know why chromeBar will prevent file manager from reacting from user tap though, this menu should have no difference compared to the document menu....

**Comment by twobob** [comment] 2013-02-21 19:40
I am no expert. 

but as I noted here: http://www.mobileread.com/forums/showpost.php?p=2429582&postcount=940 

QUOTE:

Noted that the status bar keeps "peeping through" and that the area assigned to the click is also the area assigned to the status bar...

Dropped the **killall -stop cvm** back into my kpdf.sh 
(clearly a bit risky but meh I'm testing and I can use ssh access to restart it in the event of EPIC FAIL)

now my menu works every time.?

don't suppose it could be the click is getting swallowed up?

TBH.... I would be comfortable with monitoring the HOME key and simply assuming that a HOME key click was a request to QUIT. That would be fine. Also, that being the case, one could then drop the relevant pillow/home search bar "tidy up" bits (*\* restart pillow*\* maybe?) at the kpdf.sh script end.  

Like I said... I'm no expert, was just hacking on it.

(throw rocks at the dummy now)

**Comment by houqp** [comment] 2013-02-24 06:50
@twobob thanks for the test. I guess stop pillow is enough to prevent status bar from peeping? Is it necessary to stop the cvm?

**Comment by th0mass** [comment] 2013-03-10 09:33
on the current nightly build I can't use the home button to exit from KPV. file manager menu doesn't appear also. Hence no way to exit KPV on Kindle Touch, too 

used Kindle Touch 5.3.2. and the latest nighly build available(20130308) and launched the app via KUAL

**Comment by houqp** [comment] 2013-03-11 05:21
I cannot reproduce this in my KPW and emulator. @th0mass , can you try with the latest code? (you will like it since @chrox added scroll mode for pdf/djvu)

**Comment by th0mass** [comment] 2013-03-11 18:04
scroll mode is great however the problem still exist on Touch (via KUAL)

**Comment by houqp** [comment] 2013-03-11 18:13
That's strange, I will test it again tonight.

**Comment by houqp** [comment] 2013-03-12 05:50
@th0mass , I tried with the latest KUAL and KPV, still cannot reproduce the bug. I can tap on top to invoke the home menu both before and after I open a book.

What version of KUAL are you using?

**Comment by th0mass** [comment] 2013-03-12 08:00
0.4 .
just to be sure downloaded and replaced the KUAL kindlet, result is the same.

did you disable the home button intentionally?

**Comment by houqp** [comment] 2013-03-12 15:33
No I haven't touched the filechooser at all. Just checked out the source, strangely, the it wasn't listening to home key press at the beginning... I have no idea why pressing home key works for you before ;P

Anyway, I added the home key event listener now. Also @chrox 's new RP will fix your problem :)

**Comment by th0mass** [comment] 2013-03-13 09:27
20130313: still the same problem is exist. (home key+file manager menu)

however full refresh is perfect :+1:  
thanks for your efforts so far.

**Comment by chrox** [comment] 2013-03-13 13:08
@th0mass Did you update your Kindle Touch to firmware version 5.3.2.1? It seems that in this version of firmware the Home key event is not emitted from `/dev/input/event2`. Since the event log of KPV didn't capture the `Home` event at all when one of KPV user pressed the Home button. Could you do me a favor to verify this?

**Comment by houqp** [comment] 2013-03-13 16:03
@th0mass , it will also be very helpful if you can use `evtest` command to help us find out which file is emitting home key event :)

**Comment by th0mass** [comment] 2013-03-14 16:15
@chrox yes it is 5.3.2.1 

@houqp is it sufficient to write evtest in kterm?

**Comment by houqp** [comment] 2013-03-14 16:36
@th0mass , yes, just type it in the terminal:

```
evtest /dev/input/event2
```

Then press home key to see if it gives any output

**Comment by th0mass** [comment] 2013-03-14 16:38
![Ads z](https://f.cloud.github.com/assets/1252713/259744/3aa505a8-8cc5-11e2-889a-2929b38a1320.png)

**Comment by houqp** [comment] 2013-03-14 16:47
So /dev/input/event2 does emit home key event... Could you also help us verify this bug does not exist in previous working version? I want to make sure this is a bug introduced by recent commits in KPV, not the update from amazon.

**Comment by th0mass** [comment] 2013-03-14 16:49
ok, will try now

**Comment by th0mass** [comment] 2013-03-14 16:54
home button works on gdb8872c (20130217)
works on 20130225
not works on 20130304  <<<
not works on 20130306
not works on 20130308

**Comment by houqp** [comment] 2013-03-14 19:27
Awesome, that information is very helpful!

Could you also check 20130228?

**Comment by houqp** [comment] 2013-03-15 01:17
OK, eureka at mobileread has found out which line causes the bug. Thanks a lot for your help @th0mass :)

**Comment by houqp** [comment] 2013-03-15 02:58
closing for now since patch is merged.

**Closed as completed by houqp** 2013-03-15 02:58 UTC
Labels: Next release

**Comment by th0mass** [comment] 2013-03-15 08:55
sorry I forgot to write it here, home button works on 20130228 also.. 
thanks for fixing it.
