### ISSUE TITLE
Latest nightly build will not launch

### ISSUE THREAD

**Issue by andreimariusb** [koreader/kindlepdfviewer#835] opened 2013-04-13 11:04 UTC
For some reason, if I install the latest nightly build it will not launch.
Shift-P-D will just print a Success! message (like Shift-Shift-Space). I have a K3 (keyboard).

I have reverted to the last one (before today) and it launches as it should.

**Comment by chrox** [comment] 2013-04-13 11:14
I cannot test it on K3. Could you post the content of crash.log in kindlepdfviewer folder after it crashes?

**Comment by andreimariusb** [comment] 2013-04-13 11:19
lua config error: ./reader.lua:31: module 'gettext' not found:
    no field package.preload['gettext']
    no file './gettext.lua'
    no file '/usr/local/share/luajit-2.0.0/gettext.lua'
    no file '/usr/local/share/lua/5.1/gettext.lua'
    no file '/usr/local/share/lua/5.1/gettext/init.lua'
    no file './gettext.so'
    no file '/usr/local/lib/lua/5.1/gettext.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'require'
    ./reader.lua:31: in main chunk

**Comment by chrox** [comment] 2013-04-13 11:32
It looks like a serious problem. I have deprecated the latest build and
re-upload it when fix this problem.

On Sat, Apr 13, 2013 at 7:19 PM, andreimariusb notifications@github.comwrote:

> lua config error: ./reader.lua:31: module 'gettext' not found:
> no field package.preload['gettext']
> no file './gettext.lua'
> no file '/usr/local/share/luajit-2.0.0/gettext.lua'
> no file '/usr/local/share/lua/5.1/gettext.lua'
> no file '/usr/local/share/lua/5.1/gettext/init.lua'
> no file './gettext.so'
> no file '/usr/local/lib/lua/5.1/gettext.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'
> stack traceback:
> [C]: in function 'require'
> ./reader.lua:31: in main chunk
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/koreader/kindlepdfviewer/issues/835#issuecomment-16331459
> .

## 

Huang Xin, Ph.D. student
Laboratory of Vision Restoration
School of Basic Medical Sciences
Peking University
38 Xueyuan Road
Beijing, China 100083
Tel 86-10-8280-2972
Fax 86-10-8280-2877

**Comment by chrox** [comment] 2013-04-13 11:42
It seems that koreader-base doesn't contain the gettext module which cannot be true unless that your koreader-base is an old version. Could you delete the kindlepdfviewer folder and make a fresh installation of the latest build? Sometimes it do happen when there is a koreader-base process running in the background and it will prevent unzip to override the koreader-base file. BTW. you can backup the history directory in the kindlepdfviewer directory before the delete. It contains all document-specific settings and can be used to restore those settings after installation.

**Comment by andreimariusb** [comment] 2013-04-13 11:49
Nothing changes. 
I get a "Success!" message and the crash.log is identical.

**Comment by chrox** [comment] 2013-04-13 11:55
I got it. The gettext.lua is missing in the package. You can download the file https://raw.github.com/koreader/kindlepdfviewer/master/gettext.lua and drop it to your kindlepdfviewer directory or wait for tomorrow's build.

**Comment by andreimariusb** [comment] 2013-04-13 12:03
I did it and now the crash is showing this:

lua config error: ./reader.lua:108: error opening input device <slider>: 2

**Comment by chrox** [comment] 2013-04-13 12:11
The ./reader.lua:108 has some difficulty to open the device of slider.
I have no idea how does this come out. Probably it's a problem of the code reorganization. If so @hwhw or @houqp could help you.

**Comment by hwhw** [comment] 2013-04-13 13:12
that will probably take me a day or two. But I'll dig into it.

**Comment by houqp** [comment] 2013-04-14 01:23
yeah, it's caused by API breakage of koreader-base, the slider is renamed to fake_events

**Comment by houqp** [comment] 2013-04-14 03:38
closing for now so @hwhw can concentrate working on FFI binding ;p

**Closed as completed by houqp** 2013-04-14 03:38 UTC

**Comment by mayabtlaloc** [comment] 2013-04-16 01:19
the new version "kindlepdfviewer-nightly-20130415" crashes when opening the epub. already tried it with different books and always the same. which may be the problem?

**Comment by chrox** [comment] 2013-04-16 05:20
Could you post the crash.log file in the kindlepdfviewer directory after the crash? It could be easier to locate the bug from there.

**Comment by mayabtlaloc** [comment] 2013-04-16 06:03
ok, the crash.log file contains the following:

lua config error: ./crereader.lua:264: bad argument #1 to 'drawCurrentPage' (blitbuffer expected, got userdata)

**Comment by houqp** [comment] 2013-04-16 16:39
Hi @mayabtlaloc , thanks for the report, I have sent a patch in a new PR

**Comment by mayabtlaloc** [comment] 2013-04-16 21:35
ok. thanks
