### ISSUE TITLE
History out of sync with file moved by third party

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#370] opened 2012-10-04 15:28 UTC
If some books were deleted or moved outside of kpv, the kpv history will not match the actual file location. If user tried to open a book from "L-recent opened book history" and that book has been moved, kpv will quit abnormally.

This behavior is understandable, but it can be done better. I suggest that:
1. If opening a book from recent history failed, kpv should not crash, instead should give a message and remove that history entry.
2. I don't suggest kpv to monitor file changes constantly, but there could be some commands in recent history screen to update file location manually, i.e. user can press some key to sync them when needed.

**Comment by tigran123** [comment] 2012-10-04 16:39
Interesting, when I just now tried to reproduce what you describe I get an error message "cannot open PDF file" and KPV does NOT quit abnormally, i.e. it is behaving exactly as you are suggesting. Tell me exactly the steps you perform, so I can duplicate them. What I did was:
1. Open a PDF file.
2. Close it.
3. Exit KPV
4. Rename the PDF file to a different name.
5. Start KPV again
6. Press L
7. Try to open the stale history entry
8. Message "error opening PDF file" and back to the "Last Documents" list.

**Comment by dracodoc** [comment] 2012-10-04 16:48
I should be more specific. The book I tried to open is an epub file. I tried again, opening a nonexisting pdf will have the message then back to list, but opening an epub will crash kpv.

So it could be some problem with crengine or crengine related code.

Besides, I think some sync function is still needed even opening epub will not crash kpv. Of course this is not a critical bug, so it don't have to have high priority in your list.

I noticed that kpv will update file list when it was loaded, this seemed to be a good time to sync history too, because any changes outside kpv has been updated at this time, so it should be easy to sync history at the same time, but I'm not sure if it will take too much time. It could be a problem with too many books and too many changes, but I think most time the incremental changes are minor, so even sync history changes for a long list should not take too much time.

**Comment by tigran123** [comment] 2012-10-04 16:56
Yes, you are absolutely right --- with epub files it actually coredumps ("Segmentation fault"). I can have a look at this. Labeled as bug now. Thanks for the report! :)

**Comment by tigran123** [comment] 2012-10-04 17:00
Ok, I have fixed this now. Wait for my PR in a minute...

**Comment by dracodoc** [comment] 2012-10-04 17:01
That was quick!
Thanks!

**Comment by tigran123** [comment] 2012-10-04 17:05
Actually, although I have the fix already, I have just cancelled the commit, because I must investigate to find out the real cause of the segmentation violation (I suspect it is a crengine bug) instead of masking it by my fix (my fix is simply preventing the user from opening a file from history entry if the file no longer exists).

The reason I wish to get to the bottom of this is that there is a chance we have a more serious issue here (memory corruption) and my fix will just mask the real problem. But don't worry, consider it fixed --- one way or the other I'll send my commit eventually (tomorrow the latest, assuming I'll find out the reason for this coredump by the end of today).

**Comment by dracodoc** [comment] 2012-10-04 17:08
That's all right, this problem is not critical.
How do you think the idea that sync with history when kpv is loading? At that time kpv will recognize any outside file changes, it may be a good time to sync with history too.

**Comment by tigran123** [comment] 2012-10-04 17:12
concerning sync: how exactly do you suggest that KPV should discover the new filename if the old one does not exist? Surely only the human knows what the new filename of the file is or whether it was completely deleted?

**Comment by tigran123** [comment] 2012-10-04 17:15
Ah, you mean to prompt the user to enter new filename for each stale history entry?

**Comment by tigran123** [comment] 2012-10-04 17:19
Ok, investigation finished --- I confirm that it is not our problem, but a bug in crengine --- when one passes non-existent filename to `doc->text_view->LoadDocument()` function it coredumps. So, my fix for preventing this from happening on the history entry level is perfectly valid, I'll submit it in a minute.

**Comment by dracodoc** [comment] 2012-10-04 17:23
There are several cases:
1. file deleted. Then the history entry should just be removed.
2. file moved but didn't change file name. Then the history entry should be updated with the new path. This method do have a potential problem if there is multiple file in different directory have same file name. However that case is not very good method to organize books, so I would suggest user not to do that, maybe use a slightly different file name, which also make it more clear that which version user is reading.
3. file renamed. This is more difficult to detect unless kpv check file size, date or checksum. I suggest just treat this case as file deleted. So kpv will remove the history entry of the old filename, and there is no new entry for new filename before the file is actually opened.

So the history on the book before the rename will lost, but that is understandable in this case. User should backup the history if he decided to change file name, because he will not be able to access that history through kpv anyway.

On second thought, to make things simpler, maybe you can just remove any history entry for changed file. User should use kpv itself to delete, move books whenever possible, in that case kpv can manage history entry to follow up the changes. Otherwise for changes made outside kpv, the invalid history entry should just be removed.

**Comment by tigran123** [comment] 2012-10-04 17:29
Ok, for now I think the adequate enough solution is to warn the user about the entry being stale (i.e. saying "File does not exist", as in my commit) and let him decide what to do, i.e. either to delete the entry or to manually edit it (outside kpv) to point to the new location of the file IF the data in the history entry (bookmarks, highlights, etc) are too precious to just throw them away. I think providing an extra user interface within KPV to do all this editing is not practical.

**Comment by tigran123** [comment] 2012-10-04 17:32
I decided to let the user make the final decision on whether to remove the history entry or not, instead of doing it automatically within KPV. I agree with you that in the majority of cases that would be the right thing, but in those few cases when the history entry contains very valuable data (bookmarks, highlights, in the future maybe even notes, when we support this) the user will be very upset if we just go ahead and remove the history entry without asking him.

**Comment by dracodoc** [comment] 2012-10-04 17:32
I'm not suggesting an extra user interface, but that kpv already recognize outside changes when loading, then it can try to match if any deleted file existing in history then remove it. However this method do seemed too aggressive and could lost data user still wanted.

So current solution is good, user can remove the stale entry with del key by himself if he want.

**Comment by tigran123** [comment] 2012-10-04 17:33
Yes, agreed :)

**Comment by dracodoc** [comment] 2012-10-04 17:37
Another method is still remove the entry from the history list, but just move the actual history file to a backup folder instead of deleting them. This way there will be automatic cleaning up, no need to remove entry manually, and user still have the data if he want. Of course with this there will be more and more history file build up with time. There will not be a problem with space or performance, but whether user would like this history build up depends on user's preference.

This is just a thought, not a must unless many people want this feature.

**Comment by tigran123** [comment] 2012-10-04 17:42
Yes, that is another valid possibility. But let's keep it simple for now i.e. prevent the crash, inform the user of the problem and let him decide what he wants to do next.

**Comment by tigran123** [comment] 2012-10-04 20:13
Closing the issue as the fix was merged into master.

**Closed as completed by tigran123** 2012-10-04 20:13 UTC
Labels: Bug
