### ISSUE TITLE
stubborn rename function

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#431] opened 2012-10-12 12:22 UTC
Scenario:
1) take a file, e.g. Test-rename.pdf
2) rename (Shift + R) it as follows -> eTest-rename.pdf
3) try to rename it again with the first letter replaced by the corresponding capital letter, i.e. ETest-rename.pdf
4) the case gets ignored. The name remains eTest-rename.pdf.
5) the same is true, if you try to replace a capital letter by the corresponding small letter.

Is there any reason why the sorting of file names is not case-insensitive?
As such, eTest-rename.pdf is placed after Test-rename.pdf.

**Comment by tigran123** [comment] 2012-10-12 12:46
The first thing is a  bug, I shall have a look when I come back in the
evening. The second thing casesensitivity is not a bug.

**Comment by eLiNK2gl** [comment] 2012-10-12 13:00
I know it is made by design.
I just wonder if it is of any use.
Looks like a nuisance to me.

**Comment by tigran123** [comment] 2012-10-12 13:15
Oh, I completely forgot that we are on vfat, so the kind of
rename you describe is not valid, so the first thibg is not a bug 
either. its a limitation of vfat filesystem.

**Comment by eLiNK2gl** [comment] 2012-10-12 13:28
not much of a problem, anyway.

**Comment by tigran123** [comment] 2012-10-12 15:41
As a closing remark I would like to point out that messing with case-sensitivity in an application that is expected to work on a VFAT filesystem is a very bad idea, because it may lead to subtle bugs. For example, VFAT would treat two existing files `file.txt` and `FILE.TXT` as different, but if only one of them existed, say `file.txt` then it would refuse to rename it to `FILE.TXT` because it would consider both `file.txt` and `FILE.TXT` as the "same names". So, "same names" and "same files" are not the same thing for VFAT. Sounds idiotic? Yes, certainly, but that is what you get when using non-Unix operating systems...

**Closed as completed by tigran123** 2012-10-12 15:41 UTC
