### ISSUE TITLE
one page away jump to link in pdf should work with Back key

### ISSUE THREAD

**Issue by dracodoc** [koreader/kindlepdfviewer#575] opened 2012-11-13 21:10 UTC
UPDATE: It's the problem of the pdf, not KPV. But for the special case of jump to link in next/previous page, Back key should bring user to previous page, currently it only works on links to several pages away.

I found some random underlines were showed in one pdf. 

The pdf is here
https://www.box.com/s/sohk5dih04gsmg2tyw7j

screenshot
https://www.box.com/s/f7j9b5zzz8fob0h5fuc5
https://www.box.com/s/ds65siqdx14oryo184vj

I guess these lines are actually underlined links because there are some links in this page, but the line position is off to the link position, probably because I cropped the pdf in pc.

So the issue is the link position need to recognize crop box to get the updated position

**Comment by tigran123** [comment] 2012-11-13 21:17
This is not a bug, it is a feature. Those locations with underlines actually have local links. E.g. the one under the word "selected" in your screenshot has a jump to page 27 (which is in References). If you press `L` then you will see the shortcuts corresponding to each link and pressing that shortcut key will bring you to the target destination of that local link.

Now, if you don't want to see any such underlines then you can just press `Shift-L` to disable showing them. The setting is saved for the current book only.

Btw, if you open that PDF on a PC (e.g. in evince or Adobe Reader) and hover the mouse over those words you will notice the mouse pointer change shape to indicate there is a link there.

Update: I just noticed the end of your report (was it there before? :) and see that you already know the reason. Ok, concerning the link position I see that KPV calculates it correctly (well, at least as accurate as evince and Adobe Reader), so there is no need (or in fact even a chance) to change anything. If you hover the mouse over the link and move it horizontally carefully, you will get an idea of the actual link location and see that KPV matches it perfectly.

Ok, there is a possibility that you are right and it is a bug SHARED by all three: KPV, evince (i.e. poppler) and Adobe Acrobat Reader. To decide this one would need to look closely at the way link coordinates interact with crop boxes and check PDF specification. But I seriously doubt it....

**Comment by dracodoc** [comment] 2012-11-13 21:38
I realized these lines are for the links in pdf. But they are not in the position they should be. The underline should appear under the link text, i.e. the one under "selected" is actually the link of [21-26] two lines above it. All these lines are from the links but in a shifted position.

One interesting thing is I cannot click these links in acrobat, so it seemed the pdf have something wrong so the links are not recognized by acrobat but actually recognized by KPV!

Another problem is, when I press L and use the short cut key to jump to the link position, I expect pressing Back will bring me to previous screen, but it didn't. There is no way to come back unless using page number.

**Comment by tigran123** [comment] 2012-11-13 21:41
Concerning the location --- I have just re-checked --- the correct location (i.e. the current one in the physical PDF you provided) is under the word "selected" and NOT the "[21-26]" reference above it. I.e. during the conversion you have shifted the location and there is no way to put it back. Also, I click on them in Adobe Acrobat Reader and in evince and they work fine.

However, concerning the jumps by Back --- it should definitely work unless the target is only one page away in which case it is not added to the history (as it looks like normal page turn). I will check this and get back to you.

**Comment by dracodoc** [comment] 2012-11-13 21:46
OK, it's the pdf's problem. I double checked, the link was supposed to be for [21-26], not for "selected" which doesn't make any sense. But the pdf creator somehow make the link attached to "selected". So this is the fault of pdf creator, KPV is doing nothing wrong here.

As for the jump, the link I tested is one page away and I tested the other links, the back key worked. However, I do think the back key should work for one page away too. Because the page number is not shown in KPV, after a jump user have no way to know the new page is one page away and he didn't know which direction too. He have to remember the page number of previous page to come back.

I think the jump by key should be easily recognized as not a normal page turn, even it only went to next page, because user was using a shortcut key in L mode to jump, not using page down.

**Comment by tigran123** [comment] 2012-11-13 21:47
I have just double-checked --- the jump works fine.

(when I said "correct location is 'selected'" I meant "correct" in the sense of the information encoded in the PDF file, and certainly not "correct" in the logical sense of the paper's text, of course. Btw, a very interesting paper! :)

**Comment by tigran123** [comment] 2012-11-13 21:52
Btw, it is not too hard to make Back work when returning from a target one page away from the link's location. I too found it annoying that it didn't work.... Maybe you should open a bug issue on this and it will probably get fixed. I guess we just need to either provide an extra goto() function or add an optional argument to it which forces the jump to be added to the list regardless of the distance from the current page. Doesn't seem too hard to me.

**Comment by dracodoc** [comment] 2012-11-13 21:55
I just modified the title and changed the first post a little bit. No need to open yet another issue, and the discussion here can provide some background. I guess other user can meet the pdf with wrong links too, because there are so many non-compatible pdf created by all kinds of tools....

**Comment by tigran123** [comment] 2012-11-13 21:55
Yes, thank you.

**Comment by tigran123** [comment] 2012-11-14 11:02
The fix is merged into master, closing the issue.

**Closed as completed by tigran123** 2012-11-14 11:02 UTC
Labels: Bug
