### ISSUE TITLE
kpdfviewer crashing while closing a book

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#273] opened 2012-09-11 08:12 UTC
error: "kpdfview: fitz/base_context.c:23: fz_free_context: Assertion `ctx->error->top == -1' failed.
Aborted"

1) opened a book 
2) pressed 'H'
3) pressed 'forward' to go to the second page
4) pressed 'Back' to exit the shortcut page
5) pressed 'Alt + Back' to close the book

**Comment by tigran123** [comment] 2012-09-11 09:46
This is a PDF file (because the error comes from mupdf), so would it be possible to have a copy of it, please? I tried to reproduce it on my PDF files and cannot. Also, which page do you open the book on? And will the problem persist if you delete the history entry for this book?

**Comment by eLiNK2gl** [comment] 2012-09-11 11:22
@tigran123 I cannot reproduce the problem either.
I can certainly provide you with the file but considering the crash is not reproducible it is probably not very helpful.
I'll try further.
Should you still need the book, let me know.

**Comment by tigran123** [comment] 2012-09-27 21:11
I am inclined to close this issue as it is non-reproducible. Labelling it as "Unclear" for now, in case someone thinks it is worth keeping open.

**Comment by tigran123** [comment] 2012-10-03 16:48
Closing as it hasn't been reproduced in a long time and now we have a sufficiently different application to have correspondingly different bugs :)

**Closed as completed by tigran123** 2012-10-03 16:48 UTC
Labels: Unclear

**Comment by eLiNK2gl** [comment] 2012-10-04 21:00
I did it again.
This time pressing 'H' to close a pdf book
Crash.log: "warning: ignoring transfer function
warning: ... repeated 44 times ...
kpdfview: fitz/base_context.c:23: fz_free_context: Assertion `ctx->error->top == -1' failed.
Aborted"

P.S.:2012-09

**Comment by tigran123** [comment] 2012-10-04 21:04
H? But H calls Help, not quit. Did you really mean H or maybe Home?

**Comment by tigran123** [comment] 2012-10-04 21:04
Is it easily reproducible?

**Comment by eLiNK2gl** [comment] 2012-10-04 21:32
Oops, yes I meant 'Home'.
Cannot reproduce it.

**Comment by eLiNK2gl** [comment] 2012-10-15 12:07
once again, while closing a book (press 'Home') (http://www.licht.de/fileadmin/shop-downloads/lichtwissen14_Licht_Wohnen.pdf), the kpdfviewer crashed.
This time with the following error 'warning: not building glyph bbox table for font 'DKACFN+Cambria' with 4722 glyphs'.

P.S.: kindlepdfviewer-v2012.09-200-gfd7eaf3.zip

**Comment by tigran123** [comment] 2012-10-15 12:33
This is because mupdf has a limit of 4096 for the maximum number of entries in bbox glyph table which it builds. And this PDF file has a font with 4722 glyphs (>4096), so it fails...

I wonder what would happen if we increase the `MAX_BBOX_TABLE_SIZE` to a bigger value and recompile mupdf...
