### ISSUE TITLE
page down skips portion of text in fit-to-width mode with some PDFs

### ISSUE THREAD

**Issue by otichy** [koreader/kindlepdfviewer#654] opened 2012-12-06 15:39 UTC
With some PDFs when I SHIFT+S and page down, all works fine - the rest of the current page is displayed. With some however, I jump to the next page directly, missing half of the previous page.
I tried to set the box by SHIFT+X to the whole page, toggled the P option, nothing helps. 
But as I say, only some PDFs behave this way. One that behaves in the way described is here: http://www.sendspace.com/file/6acfa9

Ondrej

**Comment by houqp** [comment] 2012-12-06 16:16
Thanks for the report. I tried several pages but still cannot reproduce the bug. Could give a more detail steps on bug reproduction? For instance go to which page and do what operation blabla...

**Comment by otichy** [comment] 2012-12-06 16:26
Funny, I tried to wipe the file from my Kindle and replace it. Now it works as expected. At least in the SHIFT+S mode, not in the S mode, but that's probably intended behaviour. Anyway, thanks for nudging me to a simple solution :)

**Comment by houqp** [comment] 2012-12-06 20:22
Yeah, some wired bugs are difficult to reproduce ;P I am closing the issue now. Please report back when you find new bugs.

**Closed as completed by houqp** 2012-12-06 20:22 UTC
Labels: Bug
