### ISSUE TITLE
emulator crashes occasionally when setting up tap timer

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#762] opened 2013-02-20 03:28 UTC
Error info is like this:

```
# in tap state... {
    ["y"] = 744,
    ["x"] = 532,
    ["timev"] = {
        ["usec"] = 973944,
        ["sec"] = 1361330361
    },
    ["id"] = 0
}
# set up hold timer
# in tap state... {
    ["y"] = 744,
    ["x"] = 532,
    ["timev"] = {
        ["usec"] = 66247,
        ["sec"] = 1361330362
    },
    ["id"] = -1
}
# set up tap timer
# in tap timer true
# in ui.lua: {
    ["handler"] = "onGesture",
    ["args"] = {
        [1] = {
            ["pos"] = {
                ["y"] = 744,
                ["x"] = 532,
                ["h"] = 0,
                ["w"] = 0
            },
            ["ges"] = "tap"
        }
    }
}
# in tap state... {
    ["y"] = 744,
    ["x"] = 532,
    ["timev"] = {
        ["usec"] = 793388,
        ["sec"] = 1361330363
    },
    ["id"] = -1
}
# set up tap timer
lua config error: ./frontend/ui/time.lua:81: attempt to index local 'self' (a nil value)
stack traceback:
    ./frontend/ui/time.lua:81: in function '__add'
    ./frontend/ui/gesturedetector.lua:213: in function 'feedEvent'
    ./frontend/ui/inputevent.lua:405: in function 'waitEvent'
    ./frontend/ui/ui.lua:193: in function 'run'
    ./reader.lua:180: in main chunk
```

This bug is hard to repeat on emulator. Probably it's even harder on real Kindle.

**Comment by houqp** [comment] 2013-02-21 14:23
I saw that crash once a few days ago, probably caused by my recent rewrite of gesturedetector. Will take a look on weekends.

**Comment by houqp** [comment] 2013-02-24 19:16
closing for now since I cannot reproduce it anymore.

**Closed as completed by houqp** 2013-02-24 19:16 UTC
Labels: Bug
