### ISSUE TITLE
New InfoMessage-concept

### ISSUE THREAD

**Issue by ghost** [koreader/kindlepdfviewer#333] opened 2012-09-28 00:08 UTC
CONCEPT: I've just finished first attempts to make InfoMessages user-configurable. In other words, new concept requires developers just to set the importance level for a certain message, while the user is suggested to tune the method to inform him about the reader events by his own hands.

ATM, messages are separated on 4 various classes enumerated in the order of importance
        a) "Auxiliary messages (e.g. 'Scanning folder...')",
        b) "Important messages (e.g. 'Already first jump!')",
        c) "Errors (e.g. 'Zip contains improper content!')",
        d) "Confirmations (e.g. 'Press Y to confirm erasing!')",

For each of these classes user may set one of the following information methods
        (i) "Avoid any notifications", 
        (ii) "Show popup window",
        (iii) "Use TTS-voice",
        (iv) "Popup window and TTS-voice".
The default values for each of them is set to (ii) that corresponds to our usual way to show text in popup windows -- either via showInfoMsgWithDelay(...) or via InfoMessage:show(...) 
If the concept will be approved, optimized and properly tested, both these functions are to be replaced by more powerful fucntion InfoMessage:inform(...) There are no need to make such a replacement simultaneously, one may do it step-by-step as soon as the time allows.    

I've also added some basic support for sending text messages to TTS-engine & adjusting sound parameters -- the sound volume & TTS-engine speed.

All necessary files -- i.e. dialog.lua, filechooser.lua & reader.lua - are uploaded in my repo https://github.com/nupogodi/kindlepdfviewer/ 

WARNING: the concept was tested and worked properly only on Kindle 3 (fw3.0.3), so any feedback -- both positive and negative -- from lucky owners of other sound-equipped Kindles (K2 & KDX) is welcome.

USING: 
1. overwrite your dialog.lua, filechooser.lua & reader.lua by new versions taken either from my repo
2. run filemanager, press Alt+M and select 'expert mode for developers & testers'
3. then press KEY_I, select the item (a)-(d) you want to tune and proper method (i)-(iv) to inform you about this type of events - the selected method will be directly illustrated by the test message.
4. The sound volume & TTS-speed might also be readily tuned -- again, only in the 'experts mode' of filemanager by pressing Vol-/+ and Shift+Vol-/+, respectively
5. Please, test also reading & saving the InfoMessage-parameters from/to settings.reader.lua
6. [Updated] Apart from the test message after changing (i)-(iv), you should also see the effect for all messages & warnings included in filechooser.lua

**Comment by tigran123** [comment] 2012-09-28 10:16
@NuPogodi Amongst your changes there is a commit which replaces the "/" shortcut with "Del" which may break "deletable" menus on a DXG. Is it really needed for the new InfoMessage implementation?

Also, among your changes there is a fix for proper scfont initialization (which will probably fix the bug I reported whereby the font used by selectmenu is not persistent (if modified by user) across exit/restart). But now you can't do a pull request for this specific fix because github.com's implementation of the interface to "git" does not allow to cherry pick a commit and send it inside a pull request.

So, someone will have to use "git cherry-pick" command to pick that fix and put it into the current stable "bugfixes only" pre-release tree.

Concerning your new InfoMessage concept --- the idea and implementation look adequate, but I will let you know if I find any problems when I have tested it (especially on DXG). (it may not be today though).

**Comment by tigran123** [comment] 2012-09-28 10:27
Another suggestion: please don't use explicit numbers (0,1,etc) as parameter values but rather something that at least looks like symbolic defines (I know that Lua doesn't have them) i.e. like MSG_WARN etc (like we have for keys KEY_ENTER etc). This is so that looking at the particular invokation of :inform() method one doesn't need to always go to the source code of implementation to remember which parameter value means what.

**Comment by ghost** [comment] 2012-09-28 10:33
> Amongst your changes there is a commit which replaces the "/" shortcut with "Del" which may break "deletable" menus on a DXG. Is it really needed for the new InfoMessage implementation?

No, it's not. I've written above that all you need to test the concept is only 3 files -- dialog.lua, filechooser.lua & reader.lua. Most of changes are made in dialog.lua, filechooser contains the hotkeys (KEY_I, Vol-/+ and Shift+Vol-/+) to run new functions and presents many examples how the new concept works with various events - auxiliary message ("Searching..."), important messages ("Unstable... Only for experts!"), errors ("This folder can not be deleted") and confirmations ("Press 'Y' to confirm deleting").

> Another suggestion: please don't use explicit numbers (0,1,etc) as parameter values but rather something that at least looks like symbolic defines (I know that Lua doesn't have them) i.e. like MSG_WARN etc

Generally, the 'explicit number' is just the importance level, it grows form 1 to 4. But it might be readily changed by adding proper definitions -- MSG_AUX, MSG_WARN, MSG_ERROR, MSG_CONFIRM -- somewhere.

UPDATED: done...

**Comment by tigran123** [comment] 2012-09-28 10:35
Ok, great :)

**Comment by tigran123** [comment] 2012-09-28 11:02
Am I right to understand that the user can't do anything while the message is being spoken? Or is "say" command intelligent enough to return immediately and simply queue the message to be spoken thus allowing the user to continue working? If it is not asynchronous (i.e. one has to wait until the message is spoken to the end before doing anything) then it would seriously irritate the end-user who would rather choose to have no voice support than to wait...

**Comment by ghost** [comment] 2012-09-28 11:08
No, user can do evethyng what he wants -- navigate between files & folders, scroll pages, etc -- when TTS-engine tells him smth. That was the reason I tried to implement TTS-feature.

**Comment by tigran123** [comment] 2012-09-28 11:14
Excellent! That is really good, now I am very impressed with TTS. I was sceptical initially because I assumed it was going to slow everything down and force the user to wait patiently for those messages to be spoken aloud :)

Well done!

**Comment by eLiNK2gl** [comment] 2012-09-28 12:25
@NuPogodi   items from history get still deleted w/o confirmation.

(In 'confirmations', 'show popup window' is selected.)

P.S.: KDXG

**Comment by ghost** [comment] 2012-09-28 13:01
@eLiNK2gl , Thanks, I certainly remember about it... It's easy to fix, but I can not submit pull request with this fix as my repo now contains mostly files -- either already adjusted or waiting for it -- with not properly tested sound-related functions. So, please, ask other developers -- it should not take too much time

PS. KDXG? May you hear just implemented TTS-warnings on DXG? May you adjust volume & change TTS-speed?

**Comment by eLiNK2gl** [comment] 2012-09-28 13:22
@NuPogodi no problem with the TSS related features.
But I've got firmware v.3.2.1.

**Comment by ghost** [comment] 2012-09-28 13:32
@eLiNK2gl , just added the confirmation you asked for to my repo https://github.com/NuPogodi/kindlepdfviewer/blob/master/filehistory.lua

If you properly and quickly test how it works, this fix might be included in the release. It looks like (line 215-...)

self.commands:add({KEY_DEL}, nil, "Del",
"delete history entry",
function(self)
file_entry = self.result[self.perpage*(self.page-1)+self.current]
if not file_entry then return end
local file_to_del = file_entry.dir .. "/" .. file_entry.name
if InfoMessage.InfoMethod[MSG_CONFIRM] == 0 then -- silent regime
os.remove(DocToHistory(file_to_del))
self:init()
self:setSearchResult(self.keywords)
else    InfoMessage:inform("Press 'Y' to confirm ", nil, 0, MSG_CONFIRM,
"Press key Y to confirm deleting.")
if FileChooser:ReturnKey() == KEY_Y then
os.remove(DocToHistory(file_to_del))
self:init()
self:setSearchResult(self.keywords)
end
end
self.pagedirty = true
end
)

**Comment by eLiNK2gl** [comment] 2012-09-28 13:55
@NuPogodi
Hmm...
I'm afraid it just works :)
Thanks

just one observation
in the file chooser, pressing 'I' envokes the list with the event types.
in the lists of 'search results' and 'last documents', pressing 'I' envokes the information on the file selected.

**Comment by eLiNK2gl** [comment] 2012-09-28 14:11
@NuPogodi 
no TTS for 'already first jump'
Actully, the popup window is shown, irrespective of what I choose.

'Registering fonts...' does not belong to the group of auxiliary messages, whereas imho it should.

**Comment by ghost** [comment] 2012-09-28 14:30
@eLiNK2gl , I must confess that I did not have enough time to check every warning (I hope that "already first jump" was attributed to this class). I can do it later, as this feature will not be included to the september release anyway. 
PS. Could you please be a bit more presice in your reports and specify what type of reader -- crereader or unireader -- you are writing about?

**Comment by eLiNK2gl** [comment] 2012-09-28 14:51
@NuPogodi  
Sorry, I will.

unireader (pdf)

**Comment by tigran123** [comment] 2012-09-28 15:10
Let us think logically and then the following will be quite clear:

The confirmation for deleting history entry is not needed --- it is not done by any standard ereader like CoolReader or Amazon's built-in mobi viewer. I thought we already discussed this and agreed that such data as bookmarks, highlights, etc are "ethemeral", i.e. user-defined custom data and if the user chooses to delete them he should not be prompted: doing so would only slow down the normal operation unnecessarily.

The books, on the other hand, are NOT "ethemeral user custom data", they are permanent/precious data external to the "User" and provided by the "Library Administrator" who gave the user access to the Library by means of the Kindle device (which serves as "Library Repository with ability to view Library items"). The fact that "Library Administrator" and "User" are normally (but not always, e.g. think of a "son + aged mother" scenario where mother is a User and son is a Library Admin) the same physical person does not change the situation, if you think carefully and logically.

Also, making the confirmation "optional" globally is a very bad idea, because some confirmations (e.g. deleting a physical file on the device) should be enforced.

Also, I don't understand what @NuPogodi means by showing a fragment of code which contains pieces of his new infrastructure and adding "it might be merged now" --- we already agreed that the new infrastructure is not to be merged until after the official stable release.

However, if you still have strong arguments for having a prompt before deleting history entry then it could be implemented without the new infrastructure for merging into the current stable tree. But I would vote against it as it is: a) not needed, imho and b) it is NOT a bugfix and now the tree is frozen except for bugfixes. Let, therefore @houqp and @dpavlin have the final word.

**Comment by eLiNK2gl** [comment] 2012-09-28 15:31
well, thinking logically, i tend to agree more with @NuPogodi.
You can easily get a copy of your book but not of your bookmarks and highlights.

I bet most users don't even know that while deleting an entry from the history they delete everything that belongs to the file, which should in my view be addressed and, as long as the issue not solved, properly communicated.
But it is just my opinion.

Reading library ebooks is not possible as kpdfviewer does not support Adobe registration.
I, like many others interested in a 9.7" ebook reader, have many scientific articles on the device.
So, I (and I trust others in a similar position) would really hate to loose my work.

But I would certainly agree with you that this feature is not to be taken lightly and should be well thought out.

Actually, I would suggest considering adding an index file to keep information on whether a file was read or not.
Removing an entry from the index file would not do any harm.
The rest of the information (bookmarks, highlights, notes (sometime in the future :)) is to be kept in a file specific lua file.

**Comment by tigran123** [comment] 2012-09-28 16:07
Let us also recall to mind the fact that Amazon Kindle framework does not prompt even when deleting a file as long as the file is known to be stored in the Amazon storage ("Archived Items"). Why? Because the book can be easily retrieved via WiFi or 3G (for free, btw, despite their claims that they would charge the fees it actually works via 3G for free, must be a bug or maybe there is some limit after crossing which they'd start charging...). But if the book is not known to the storage then the user is prompted before deleting.

So, Amazon framework treats books as precious non-restorable entities unless it knows that there is a copy in their storage. But it does not treat the annotations in the same way (regardless of whether the option "backup annotations" is ticked or not).

I think what you are suggesting in the last paragraph would perhaps be equivalent to something else, namely to exporting user annotations to an external file and NOT touching that file at all, like "My Clippings.txt" on Kindle. Then, I would argue that until the user chooses to _export_ his annotations he treats them as _ethemeral_ ("short-lived") and should not be prompted before deleting them. But if he chose to export them then he must have treated them as important enough and so they should be "beyond" our jurisdiction, so to speak. What do you think?

**Comment by tigran123** [comment] 2012-09-28 16:16
Ah, I see what you mean: to have two files in history directory for each book -- one which contains short-lived stuff like last page read, render_mode, globalzoom, jump_history, bbox etc (which can be set up with each reading session if need be) and another file which contains precious long-lived data like bookmarks, highlights and (in the future) notes. To this I would gladly agree and help to implement it. But this looks like a serious post-release type of change, certainly not a "last minute change to go into release". Agreed?

**Comment by ghost** [comment] 2012-09-28 16:41
> The confirmation for deleting history entry is not needed ... some confirmations (e.g. deleting a physical file on the device) should be enforced.

We have already discussed this task on the Russian forum. I wrote my arguments Pro (just saving 2 page refreshes that could also in future be avoided in TTS-regime) and Contra (loosing results of the whole work performed at reading -- bookmarks, stored fragments, bounding boxes, etc) NOT to ask user before deleting the history file. I also wrote that each reasonable user (including you and me) has backup for own library, but no backup for history files. Now I again sending me to look on other readers. I regret but it's not too constructive idea since even native reader stores clippings into separate file in the documents-folder and asks user whether he wants to delete it or not...

> Also, I don't understand what @NuPogodi means by showing a fragment of code which contains pieces of his new infrastructure and adding "it might be merged now"

The second branch of the presented code is just a confirmation that, if necessary, could be readily cherry-picked into the next release.

**Comment by tigran123** [comment] 2012-09-28 16:59
My argument against prompting the user is not about saving two page refreshes, but saving several minutes of user's time who is deleting a thousand entries from the history --- without prompt it can be done quickly by just keeping the finger on the "Del" key. Otherwise it take minutes...

**Comment by ghost** [comment] 2012-09-28 17:35
Well, I have already thought to implement selecting and processing multiple files in filechooser.lua - imho, it's the right way to solve this task, but not the silent deleting that could happen even accidentally if I'll be so stupid to carry my K3 not protected by а rigid cover somewhere in the bag.

**Comment by tigran123** [comment] 2012-09-28 17:41
Yes, selecting multiple files (btw, how do I press INS key in myts to get selection in mc?) is a good idea.

**Comment by ghost** [comment] 2012-09-28 17:57
I don't know how to select one file, I always used for multiple selections mostly the key "*" (Back+I) as well as "+" (Back+S), "-" (Back+F)
PS For multiple selection in filechooser I was going to use Space (as in totalcmd), but left this task till better times

**Comment by ghost** [comment] 2012-09-28 18:53
BTW, if looking for easiest implementation of multiple file deleting... One may add Shift+Del to filesearcher that would delete ALL found items. If one needs to erase few thousands of history files, he just has to set filechooser in the Advanced mode (that searches among files with any extentions), then enter folder ./history, run filesearcher with the pattern " " (or "lua" or any other) and finally Shift+Del to delete all found results. This way we have even not to pay attention to folders as these are just out of found items.

**Comment by tigran123** [comment] 2012-09-28 18:59
Actually, that would be a very good idea, except there is one problem --- the horrible long filename of the lua file in history. I.e. one would still need to press fiveway Right to ascertain what book this file corresponds to and then delete it.

**Comment by eLiNK2gl** [comment] 2012-09-29 14:38
Actually, what I suggested is to have one file (which I called an index file) to contain either short-lived info (like whether a file is to be shown in the 'last read' list) or info which would be common to all files (but settings could be a more proper place). It can also be used later when collections would be supported (one of the issues on @houp's priorities' list). The info peculiar to each file is to be found in filename.lua files.

This way you can easily delete your files from the 'last read' without prompt.
The bookmarks, highlights, etc remain intact.

Hope it is clearer now.

**Comment by tigran123** [comment] 2012-10-07 14:54
The code for InfoMessage:inform() API (aka "InfoMessage New Concept") is already merged into the master, so we can close this issue now. Separate issues should be opened for each bug discovered.

**Closed as completed by tigran123** 2012-10-07 14:54 UTC
Labels: Feature
