### ISSUE TITLE
imposition of text in info box

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#294] opened 2012-09-19 08:42 UTC
The text from the info box (press 'menu') is overlaid over the book's text (epub), which makes it hardly readable.
Calling up the info box for the second time helps.

**Comment by tigran123** [comment] 2012-09-19 09:40
@eLiNK2gl Are you sure that you tested it on a real Kindle and not in the emulator? In the emulator this is just a quirk of SDL (press Menu a couple of times to make it go away) but if you reproduced this behaviour on a real Kindle (or DXG) then it is a bug.

**Comment by eLiNK2gl** [comment] 2012-09-19 12:58
@tigran123 yes, sir

P.S.: mine is a DXG.

**Comment by tigran123** [comment] 2012-09-19 14:44
I am back. I see what is happening here: it is not a SDL quirk, but a side effect of retrieving TOC on the first press of Menu because the info at the bottom wants to show which section the current page belongs to and this involves generating TOC which then causes a refresh of the current page. Ok, leave this one with me also, I'll see how to fix it...

**Comment by tigran123** [comment] 2012-09-19 15:07
Ok, I have fixed this bug, so it will be in my next pull request which will also include the highlight deletion from the list.

I also fixed another bug: if the file has external links in the TOC then Menu info shows the wrong section. This will also be in the same pull request.

Now, I am focusing on the highlight deletion from the list feature which you raised in another issue.

**Comment by eLiNK2gl** [comment] 2012-09-19 16:23
fantastic, thanks

**Comment by tigran123** [comment] 2012-09-19 16:33
All fixes are in the pull request #296 now, so I am closing this issue.

**Closed as completed by tigran123** 2012-09-19 16:33 UTC
Labels: Bug
