### ISSUE TITLE
option 'Bugs' crashes kpdfviewer

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#477] opened 2012-10-21 09:44 UTC
steps:
1) press 'I' in the file chooser
2) press 'T' ('Bugs')
3) crash results (nothing is written to the crash.log)

**Comment by tigran123** [comment] 2012-10-21 09:50
I can't reproduce it. I assume you did this:
1. `rm settings.reader.lua history/*`
2. Startup KPV
3. `Alt-M` to set Expert privilege level
4.  `I` and select Bugs

If you did anything else in addition to the above minimal sequence then you must provide that info. Thanks!1

**Comment by eLiNK2gl** [comment] 2012-10-21 10:05
@tigran123
all except for the item 1

**Comment by tigran123** [comment] 2012-10-21 11:04
@eLiNK2gl Ok, then try re-producing it with step 1 included. I have just tried on Kindle as well as on emulator and I can't reproduce it. If you have settings files then it is possible that some of the values point to TTS functions and that is why it crashes, so we'll have to check all combinations. But if you reproduce it with a clean state (no settings files) then it is a different matter.

**Comment by eLiNK2gl** [comment] 2012-10-21 12:23
@tigran123
removing both settings.reader.lua and history/\* solves it

**Comment by tigran123** [comment] 2012-10-22 19:02
Ok, closing the issue until you can reproduce it with a clear sequence of steps.

**Closed as completed by tigran123** 2012-10-22 19:02 UTC
