### ISSUE TITLE
cannot return to home screen on paperwhite

### ISSUE THREAD

**Issue by chrox** [koreader/kindlepdfviewer#788] opened 2013-03-12 13:37 UTC
To reproduce this bug you could open a PDF file either with KPVBooklet from the home screen or running directly from SSH. Then press the power button to let the kindle go into screensaver. There is no problem until you press the power button again. For native kindle reader it will prompt the user "swipe to unlock kindle", and for KPV it will return to KPV reader immediately which should be a good feature. But after getting out of screensaver in this way in KPV the "return to file manager" option in document menu will fail to bring users to the home screen. Current workaround is clicking or swiping at the bottom of the screen as the users do when unlocking the kindle in native system, or pressing the power button and get out from another screensaver.

**Comment by chrox** [comment] 2013-03-17 02:12
Anybody knows that if there is a lipc command that could wake up Kindle directly from screensaver without the "swipe to unlock" touch?

**Comment by houqp** [comment] 2013-03-17 03:15
cannot reproduce this, do I need to stay in SS for long enough period of time?

**Comment by chrox** [comment] 2013-03-17 03:21
No, I press the power button in KPV reader to send the device to screensaver and press the power button again in the screensaver. It will switch back to KPV reader directly but now I cannot return to the home screen any more unless I touch the bottom of the screen. 

p.s. Launching KPV from KPVBooklet and SSH both have this problem.

**Comment by houqp** [comment] 2013-03-17 03:52
strangely, i even cannot see the swipe to unlock screen in native system... I remember saw it once long time ago...

you should probably ask this in MR ;p

**Comment by chrox** [comment] 2013-03-17 03:57
Oh, I forgot to say that my Kindle includes special offers or ads.

**Comment by houqp** [comment] 2013-03-17 04:06
Aha, I see, I have never connected my PW to internet since I reset it...

**Comment by chrox** [comment] 2013-03-17 06:32
How about sending a fake touch event at the screen bottom when lipc-wait-event get a outOfScreenSaver event?

**Comment by chrox** [comment] 2013-03-17 11:45
The fake tap hack works on Paperwhite. But I didn't test it on KT. Hope it will also work. PR sent at #811.

**Comment by houqp** [comment] 2013-03-17 15:59
closing for now.

**Closed as completed by houqp** 2013-03-17 15:59 UTC
Labels: Bug, Next release
