### ISSUE TITLE
Djvu: make it crisp please ...

### ISSUE THREAD

**Issue by eLiNK2gl** [koreader/kindlepdfviewer#217] opened 2012-06-27 09:23 UTC
the quality of text rendering in djvu files is currently sub par compared to pdf files.
The text (especially in small font) looks blurry and of low quality.
Viewing the files in WinDjView on PC is very comfortable.

**Comment by tigran123** [comment] 2012-07-06 20:13
I suspect the reason for this is that the rendering is done always with DDJVU_RENDER_COLOR in djvu.c:handle().

To handle this issue in libdjvu (a djvu viewer I wrote for Hanlin/Lbook V3 "ancient" ereaders) I set the rendering mode to MASKONLY if it is a JB2 bitonal DjVu and to COLOR otherwise, like this:

   if (page_type == DDJVU_PAGETYPE_BITONAL)
        djvu_render_mode = DDJVU_RENDER_MASKONLY;
    else
        djvu_render_mode = DDJVU_RENDER_COLOR;

where page_type is the value returned by ddjvu_page_get_type(djvu_page), where djvu_page is returned by ddjvu_page_create_by_pageno(), i.e. page->page_ref in your source code.

I suggest to test the above UNTESTED fix and if it fixes the problem (I think it should), implement it. The test files to see the difference are here:

  http://www.bibles.org.uk/testfile.zip

Note that the problem is seen only on extremely high quality files like the above test case (i.e. very high resolution bitonal data).

**Comment by tigran123** [comment] 2012-07-06 20:20
I forgot to mention how to use the above testfile.zip --- it contains a djvu and pdf versions of exactly the same high quality bitonal data. Viewing the PDF file (and adjusting gamma appropriately) results in very crisp, high contrast image. But viewing the djvu file (with whatever value of gamma --- irrelevant) shows a very grey, low contrast text on the page.

**Comment by dpavlin** [comment] 2012-08-26 17:44
@tigran123 would you mind submitting pull request for this code? I'm having trouble attributing code to you since you don't have any commits in repository :-)

**Comment by tigran123** [comment] 2012-08-26 21:08
I just looked in the release announced on the-ebook.org and the code for render_mode support was committed wrongly, namely in the UniReader:toggle_render_mode() function we should have:

self.render_mode = 1 - self.render_mode
    self:clearCache()
    self.doc:cleanCache()
    self:redrawCurrentPage()
    showInfoMsgWithDelay("New render_mode = "..self.render_mode, 1000, 1)
    self:redrawCurrentPage()

and you have only the first line and the "showInfo..." line, but missed the most important lines which clear/clean caches and redraw the current page. Without these lines the value of render_mode will only take effect on the next open of the file.

**Comment by tigran123** [comment] 2012-08-26 21:18
Oops, small correction --- obviously there is NO NEED to redraw the page TWICE. Only ONCE is more than enough! :)

**Comment by dpavlin** [comment] 2012-08-27 09:49
Thanks for correction, does code attached to #229 look OK to you now?

**Comment by dpavlin** [comment] 2012-08-27 19:09
latest master has chagnes correctly contributed to @tigran123 with nice commits. Thanks a lot for going through hurdles of first github contribution :-)

**Closed as completed by dpavlin** 2012-08-27 19:09 UTC
Labels: Bug
